// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLqr3tnPr0oEDsEpntYCHUdN9-zUfJFzQ',
    appId: '1:237460590715:web:XXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '237460590715',
    projectId: 'jo-service1',
    authDomain: 'jo-service1.firebaseapp.com',
    storageBucket: 'jo-service1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcDefGhIjKlMnOpQrStUvWxYz123456789',
    appId: '1:123456789:android:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'jo-service-app-dev',
    storageBucket: 'jo-service-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLqr3tnPr0oEDsEpntYCHUdN9-zUfJFzQ',
    appId: '1:237460590715:ios:9cc5cc3bf21cf73c7452de',
    messagingSenderId: '237460590715',
    projectId: 'jo-service1',
    storageBucket: 'jo-service1.appspot.com',
    iosBundleId: 'com.ameralnajdawi.joServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:237460590715:ios:XXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '237460590715',
    projectId: 'jo-service1',
    storageBucket: 'jo-service1.appspot.com',
    iosClientId: '237460590715-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.ameralnajdawi.joServiceApp',
  );
}
